# Generated by Django 4.1 on 2023-06-16 01:06

from django.db import migrations, models
import shop.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('Обработка заказа', 'Orderprocessing'), ('Доставка заказа', 'Orderdelivery'), ('Заказ завершён', 'Ordercompleted')], default='Обработка заказа', max_length=50, verbose_name=shop.models.order.StatusOrder),
        ),
    ]
